version: "3.8"

services:
  app:
    image: project-juice:latest
    build: ./project-juice-2.0
    restart: always
    ports:
      - "8081:80" # Twoja strona będzie dostępna dla Nginxa na tym porcie
